name: Circuit Simulation Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++
      run: sudo apt-get install -y g++

    - name: Build and test
      run: |
       g++ -std=c++11 -o SourceFiles/simulationMain SourceFiles/simulationMain.cpp
        ./SourceFiles/simulationMain "Tests/libFile.lib" "Tests/TestCircuit1/testCircuit1.cir" "Tests/TestCircuit1/stimFileCirc1.stim" "Tests/TestCircuit1/outputSimulation1.sim" "Tests/commonoutput.sim"
